### ISSUE TITLE
Load a board, go back to selector, load a board... now there are two boards in viewer

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-explorer#10]
Load a board in the board-explorer, then go back to the board selector by clicking on the board title, then pick a second board. When the board viewer portion loads, there will be two boards displayed. There should be only one.

![image](https://user-images.githubusercontent.com/742584/27343034-9bb40aa8-5596-11e7-89ea-2bb86edf44df.png)

**Comment by juliocri** [comment]
weird it happens randomly. (but looking).

**Comment by jketreno** [comment]
Fixed with changes in board-viewer to prevent older async loads from stacking and executing the code to inject into the DOM more than once.
