### ISSUE TITLE
Add "Keywords" and "Components" into filterControl radiobox

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-explorer#15]
Thoughts on improving the interaction of selecting and filtering...

Let the user pick between filter by keywords and components in the filterControl radio control group. Once selected, the list of items should be the first level of filtering. Eg., if they pick "keyword" it would list all of the keywords, however it would not be showing/hiding the list of components that match that keyword when the user hovers. It would addFilter/removeFilter in the board-viewer... it just shouldn't be showing all of the components in the left-panel.

Rather than have the "category" show up as a drop down, when "category" is selected, it would hide what is currently in the left panel and just show buttons for the various categories. If the user hovers over them, it would then addFilter/removeFilter.

In this way, keywords, components, and categories can all be visualized and interacted by the user using the same mechanics.

If the user clicks on one of the buttons, instead of listing all of the components that match no the left-panel, it should set the board-viewer::selected array to contain the items that that keyword/component/category would select.

Thoughts?

**Comment by juliocri** [comment]
@jketreno after see the example in the weekly sync, personally I do not like the categories in buttons, but the true is that increases UI homogeneity, and decreases a little bit the complexity of the selecting and filtering at the end is good.

**Comment by jketreno** [comment]
I felt the same way--especially in regard to how it looks. I *did* like being able to hover over the categories to see what things get highlighted in the board without having to click them though.

As I was working through making the UI consistent made me realize that from the board-explorer stand point, the only difference between a KEYWORD, COMPONENT, PIN, and CATEGORY is how/where it shows it in the left-panel. The API for adding/removing them from being in the active selection list could all be the same. I added a *lot* of complexity in board-explorer due to the evolution of the API and functionality; a lot of the work going on in the *Over, *Out, *Tap code can be simplified and pushed to board-viewer instead of board-explorer having to do it.

**Comment by jketreno** [comment]
Implemented in latest board-explorer/board-viewer(v0.0.24)
