### ISSUE TITLE
Tapping a component button that contains only a refdes doubles the text

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-explorer#22]
On the Quark D2000 board, tap on J11 in the component view.

It toggles from this:

![image](https://user-images.githubusercontent.com/742584/27879477-9ff5496a-6176-11e7-8676-a49602995430.png)

To this:

![image](https://user-images.githubusercontent.com/742584/27879484-a9ad1492-6176-11e7-9b0d-1ffb52ffaaeb.png)

I think it might be due to the `itemClassList` function, or perhaps `this.updateStyles()` needs to be called after an item is selected?

**Comment by juliocri** [comment]
@jketreno I tried with ```this.updateStyles()``` without success, also I saw the ```itemClassList``` function and I think the logic in there is ok, I did a conditional showing of the name: https://github.com/Board-Explorer/board-explorer/pull/24

**Comment by jketreno** [comment]
Looks like a good fix. It must not be triggering the re-evalutation of the `class$="[[itemClassList()]] ..."` function when the item changes. Maybe it isn't supported in Polymer.

A style comment about your patch:
```html
<template is="dom-if" if="{{itemClassList(item)}}"><div>[[itemName(item)]]</div></template>
```

Since `{{foo}}` indicates a two-way binding, and computed bindings are one-way, I try and use `[[foo]]` to visually indicate that the binding is one-way. I don't know that it results in any internal improvement in Polymer for how the value is hooked up though.

Even the Polymer docs are inconsistent on usage of one-way and two-way syntax when hooking up computed bindings, so there doesn't appear to be a "right way" -- I do like having the intent used when declaring the binding though. Useful for variables as well.

**Comment by jketreno** [comment]
Fixed.
