### ISSUE TITLE
Selecting a category does not let you interact with the category items

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-explorer#26]
If you load a category, for example [quark_mcu_dev_kit_c1000/system-configuration-and-user-controls-and-indicators](https://board-explorer.github.io/board-explorer/#quark_mcu_dev_kit_c1000/system-configuration-and-user-controls-and-indicators), the items are selected correctly on the board:
 
![image](https://user-images.githubusercontent.com/742584/27923716-2f6b3ca4-6234-11e7-9870-a299ba504c06.png)

However, you cannot interact with the selected items beyond hovering. You should be able to click any selected item and have the documentation for that item load.

I'm not sure if this is a board-viewer or board-explorer bug, so filing under board-explorer for now.

**Comment by juliocri** [comment]
In progress...

**Comment by jketreno** [comment]
Fixed.
