### ISSUE TITLE
If URL contains a filter list, category should be set to containing category.

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-explorer#4]
If a filter list is specified in the URL, the first category should be picked that contains all of the elements in the filter list. If no category contains all of the elements, the filterControls mode should be set to "All filters"

For example, on the Quark D2000, if the URL contains #quark_mcu_dev_kit_d2000/J22Pin7, the category should be set to "Main expansion options" and J22 Pin 7 should be selected. If the URL contained #quark_mcu_dev_kit_d2000/J22Pin7,ACCEL then "All filters" should be set and both J22 Pin 7 and ACCEL should be selected.

**Comment by jketreno** [comment]
Related to this issue, if an URL was being set, it was subsequently being filtered/cleared when the category was set during page load. Commit 5eb2253 changes that behavior.

**Comment by juliocri** [comment]
@jketreno, I wonder if the next behaviour could be a better fit:

1. if category selected, the ```uri => #[board]/[category-slug]```  (and category filter rendered.)
2. if category selected and component(s) selected ```uri => #[board][category-slug]/[[componen1],[...],[compoenentN]]``` (category filter and components selected are rendered).
3. while 'all filters' screen is active, selecting components will append the component name in the uri as normally used to do ```uri => #[board]/[[componen1],[...],[compoenentN]]``` 

My only concern in here is that we limit the user to only select the available components or keyword associated with the category selected, (while user is in the category screen) and to interact with all components the user must to check 'all filters' radio.

what do you think?

**Comment by jketreno** [comment]
Closing; interaction changed with more recent versions and this issue no longer applies
