### ISSUE TITLE
Clicking in the components panel on the left should be possible after an item is selected

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-explorer#48]
If you select a component or item in the left panel, you should be able to click on other items in the left panel without having to deselect the current item by clicking on it.

**Comment by juliocri** [comment]
@jketreno, in the next branch: https://github.com/Board-Explorer/board-explorer/compare/fix-48, I'm letting the left panel buttons enabled when a component is selected, with that, the selection is now allowed to change, but I wonder if we need to put an identifier or reuse other styles for the button that matches the refdes selected (when hover out the button all the buttons look as the same way), and do we need to allow the change of the selection by clicking on the board? or is ok only with the left panel buttons?

**Comment by jketreno** [comment]
What if we add a "selected" attribute to all the items selected, and instead of disabling all the other buttons, remove the "selected" attribute from all of those. We can then style `[selected]` for items (bolding the text or something)

Minimally tested patch trying the above:
```patch
diff --git a/src/board-explorer-app/board-explorer-app.html b/src/board-explorer-app/board-explorer-app.html
index bc79e40..57a924b 100755
--- a/src/board-explorer-app/board-explorer-app.html
+++ b/src/board-explorer-app/board-explorer-app.html
@@ -158,6 +158,11 @@ limitations under the License.
       color: #888;
     }
 
+    #layout paper-button[selected] {
+      font-weight: bold;
+    }
+
     #layout paper-button.hover,
     #layout paper-button:hover {
       background-color: #404040;
@@ -954,10 +959,10 @@ document.addEventListener("WebComponentsReady", function() {
         this.updateRoute(this.board, selected, null);
         return;
       }
-      /* Disable all items in the currently viewed page
+      /* Remove 'selected' for all items in the currently viewed page */
       Array.prototype.forEach.call(this.$.layout.querySelectorAll("paper-button"), function(el) {
-        el.disabled = true;
-      });*/
+        el.removeAttribute("selected");
+      });
 
       var active = null;
 
@@ -975,7 +980,7 @@ document.addEventListener("WebComponentsReady", function() {
       if (isCategory && this.category) {
         /* Enabling category button */
         Array.prototype.forEach.call(this.$.layout.querySelectorAll("paper-button[match='"+ this.category.slug +"']"), function(el) {
-          el.disabled = false;
+          el.setAttribute("selected", true);
         });
 
         this.active = this.boardInfo;
@@ -988,7 +993,7 @@ document.addEventListener("WebComponentsReady", function() {
       selected.forEach(function(refdes) {
         /* Enabling the button that matches this refdes */
         Array.prototype.forEach.call(this.$.layout.querySelectorAll("paper-button[match='"+ refdes +"']"), function(el) {
-          el.disabled = false;
+          el.setAttribute("selected", true);
         });
 
         /* Check if it is a component/pin... */
```

**Comment by jketreno** [comment]
@juliocri With the above, we can still have multiple items selected, and the touch interaction seems to be working (at least when playing with the panel on the left -- I didn't play with interacting with the board-viewer to see if selecting/deselecting the components in the left is intuitive or works.)

I just tested if URL loading selects items correctly with the above patch, and it doesn't -- so you'll have to hook up that code path. For example, [MinnowBoard D2,JP1](http://supercube.jf.intel.com:8081/#minnowboard_turbot_B_41/D2,JP1) should take you to the MinnowBoard, highlight D2 and JP1 in the board-viewer, and select them in the `Components` list.
