### ISSUE TITLE
Title and filterControl aren't wrapping on IE11

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-explorer#5]
On IE, the title and filterControl boxes are not wrapping correctly:

![image](https://user-images.githubusercontent.com/742584/26984070-b7b8a9cc-4cf2-11e7-8510-85b5a22d4a46.png)

On Chrome and Firefox they wrap fine. 
![image](https://user-images.githubusercontent.com/742584/26984119-f08131c0-4cf2-11e7-8485-8743eda92bf5.png)

**Comment by juliocri** [comment]
Only in IE 11 the search box is not looking good:

![capture](https://user-images.githubusercontent.com/8356225/29331466-2179cbbc-81c2-11e7-8762-71190a8e8d89.png)

**Comment by jketreno** [comment]
I think it looks fabulous! :)
