### ISSUE TITLE
Remove JTAGSEL as a selectable item in QD2000 and add JTAGSEL as a keyword 

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-explorer#51]
JTAGSEL is selectable, but then the internal components are not; to remain consistent in the UX, since we don't support multiple levels of nesting, remove JTAGSEL as a hoverable and use it as a keyword on the items in the JTAGSEL area.

**Comment by juliocri** [comment]
@jketreno only for confirm the expected result of this,

the change is basically remove the JTAGSEL item from components, and add the JTAGSEL keyword into the keywords set, and then, hovering that keyword, the resulting highlight will be something like the below:

![screen shot 2018-01-22 at 11 12 08](https://user-images.githubusercontent.com/8356225/35234093-95206172-ff65-11e7-8dc3-388835c64d56.png)

**Comment by jketreno** [comment]
@juliocri Yes. That looks great.

**Comment by jketreno** [comment]
Merged and online.
